### ISSUE TITLE
Wrong content in Listing 6.11 + small typo

### ISSUE THREAD

**Issue by schoderer** [theembeddedrustacean/ser-std#1]
**Describe the error**
The code in Listing 6.11 (page 107) shows the peripheral configuration code instead of the application loop (aka Listing 6.10 and 6.11 show the same code).

Small typo on page 74 in the first paragraph of the page: "[...] This is becuase [...]

**Error Location**
Listing 6.11 (page 107) - version v1.0 (May 16, 2024)

**Comment by theembeddedrustacean** [comment]
Thank you! The error will be addressed in the upcoming revision. This issue will be kept open until then.

**Comment by theembeddedrustacean** [comment]
Closing issue. These have been addressed in the v1.1 release of the book.
