### ISSUE TITLE
Error in variablenaming in listing 7.6 + typo

### ISSUE THREAD

**Issue by schoderer** [theembeddedrustacean/ser-std#2]
**Describe the error**
In listing 7.6 there is a error in in the variable naming in the lines 27 and 29.
The `subscribe`/`enable_interrupt` methods are called on a variable named `some_pin` but i think they should be called on `some_timer`?

A typo on page 117 in the paragraph above listing 7.5: "[...]exists a method coutner() that[...]"

**Error Location**
- page 119, listing 7.6, lines: 27, 29, version 1.0
- page 117, version 1.0

**Comment by theembeddedrustacean** [comment]
Closing issue. These have been addressed in the v1.1 release of the book.
