### ISSUE TITLE
Broken AliExpress Link for Push Button in Hardware Component List

### ISSUE THREAD

**Issue by wubin28** [theembeddedrustacean/ser-std#5]
**Describe the error**
The AliExpress link provided for the Push Button component in the Hardware Component List (Optional) section is broken, leading to a “Page Not Found” error.

**Error Location**
The error is located in the “Hardware Component List (Optional)” section of the [ser-std GitHub repository](https://github.com/theembeddedrustacean/ser-std).

**Screenshots**
![IMG_8341](https://github.com/user-attachments/assets/766b4da5-700e-428e-a8d6-54c1de942422)
Note: The screenshot above illustrates the “Page Not Found” error encountered when clicking the Push Button link.

**Comment by theembeddedrustacean** [comment]
Thank you for reporting! This has now been fixed.
