### ISSUE TITLE
Unable to run the blinky example on my ESP32C3-DevKit-M-1 SoC

### ISSUE THREAD

**Issue by nsengupta** [theembeddedrustacean/ser-std#6]
**Describe the bug**
When I execute `cargo run`, it fails to finish the build

**To Reproduce**

1.  `git pull` to be on the latest of the right branch
`On branch esp32c3dkm1
Your branch is up to date with 'origin/esp32c3dkm1'`
2. Execute `cargo run`

**Expected behavior**
The build should complete and the binary should be flashed. 

**Screenshots**
`error: failed to run custom build command for 'esp-idf-sys v0.35.0'

Caused by:
  process didn't exit successfully: '/tmp/cargo-installdX74wL/debug/build/esp-idf-sys-cb8b81113b1f0ce2/build-script-build' (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=ESP_IDF_TOOLS_INSTALL_DIR
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG_DEFAULTS
  cargo:rerun-if-env-changed=MCU
  cargo:rerun-if-env-changed=ESP_IDF_SYS_ROOT_CRATE
  cargo:rerun-if-env-changed=ESP_IDF_VERSION
  cargo:rerun-if-env-changed=ESP_IDF_REPOSITORY
  cargo:rerun-if-env-changed=ESP_IDF_CMAKE_GENERATOR
  cargo:rerun-if-env-changed=IDF_PATH
  cargo:rerun-if-env-changed=EXTRA-COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENT_MANAGER
  cargo:warning=`cargo metadata` exited with an error: error: could not find `Cargo.toml` in `/tmp` or any parent directory
  Python 3.10.12
  pip 24.3.1 from /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/pip (python 3.10)
  Requirement already satisfied: pip in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (24.3.1)
  Requirement already satisfied: setuptools in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (71.0.0)
  Collecting setuptools
    Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
  Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
  Installing collected packages: setuptools
    Attempting uninstall: setuptools
      Found existing installation: setuptools 71.0.0
      Uninstalling setuptools-71.0.0:
        Successfully uninstalled setuptools-71.0.0
  Successfully installed setuptools-75.6.0
  Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi
  Ignoring importlib_metadata: markers 'python_version < "3.8"' don't match your environment
  Collecting setuptools (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 3))
    Using cached https://dl.espressif.com/pypi/setuptools/setuptools-71.0.0-py3-none-any.whl (908 kB)
  Requirement already satisfied: packaging in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 4)) (24.2)
  Requirement already satisfied: click in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 7)) (8.1.7)
  Requirement already satisfied: pyserial in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 8)) (3.5)
  Requirement already satisfied: cryptography in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 9)) (39.0.2)
  Requirement already satisfied: pyparsing in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 10)) (3.0.9)
  Requirement already satisfied: pyelftools in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 11)) (0.29)
  Requirement already satisfied: idf-component-manager in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (2.0.4)
  Requirement already satisfied: esp-coredump in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 13)) (1.12.0)
  Requirement already satisfied: esptool in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 14)) (4.7.0)
  Requirement already satisfied: esp-idf-kconfig in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 15)) (1.4.3)
  Requirement already satisfied: esp-idf-monitor in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 16)) (1.5.0)
  Requirement already satisfied: esp-idf-size in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 17)) (1.6.1)
  Requirement already satisfied: esp-idf-panic-decoder in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 18)) (1.2.1)
  Requirement already satisfied: construct in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 19)) (2.10.70)
  Requirement already satisfied: freertos_gdb in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from -r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 22)) (1.0.3)
  Requirement already satisfied: cffi>=1.12 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from cryptography->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 9)) (1.17.1)
  Requirement already satisfied: colorama in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (0.4.6)
  Requirement already satisfied: pyyaml in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (6.0.2)
  Requirement already satisfied: requests in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (2.32.3)
  Requirement already satisfied: requests-file in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (2.1.0)
  Requirement already satisfied: requests-toolbelt in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (1.0.0)
  Requirement already satisfied: tqdm in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (4.67.0)
  Requirement already satisfied: jsonref in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (1.1.0)
  Requirement already satisfied: pydantic in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (2.10.0)
  Requirement already satisfied: pydantic-core in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (2.27.0)
  Requirement already satisfied: pydantic-settings in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (2.6.1)
  Requirement already satisfied: typing-extensions in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (4.12.2)
  Requirement already satisfied: pygdbmi>=0.9.0.2 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from esp-coredump->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 13)) (0.11.0.0)
  Requirement already satisfied: bitstring>=3.1.6 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from esptool->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 14)) (4.2.3)
  Requirement already satisfied: ecdsa>=0.16.0 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from esptool->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 14)) (0.19.0)
  Requirement already satisfied: reedsolo<1.8,>=1.5.3 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from esptool->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 14)) (1.7.0)
  Requirement already satisfied: intelhex in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from esptool->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 14)) (2.3.0)
  Requirement already satisfied: kconfiglib>=13.7.1 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from esp-idf-kconfig->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 15)) (14.1.0)
  Requirement already satisfied: rich in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from esp-idf-size->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 17)) (13.9.4)
  Requirement already satisfied: bitarray<3.0.0,>=2.9.0 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from bitstring>=3.1.6->esptool->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 14)) (2.9.3)
  Requirement already satisfied: pycparser in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from cffi>=1.12->cryptography->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 9)) (2.22)
  Requirement already satisfied: six>=1.9.0 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from ecdsa>=0.16.0->esptool->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 14)) (1.16.0)
  Requirement already satisfied: annotated-types>=0.6.0 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from pydantic->idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (0.7.0)
  Requirement already satisfied: python-dotenv>=0.21.0 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from pydantic-settings->idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (1.0.1)
  Requirement already satisfied: charset-normalizer<4,>=2 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from requests->idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (3.4.0)
  Requirement already satisfied: idna<4,>=2.5 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from requests->idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (3.10)
  Requirement already satisfied: urllib3<3,>=1.21.1 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from requests->idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (1.26.20)
  Requirement already satisfied: certifi>=2017.4.17 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from requests->idf-component-manager->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 12)) (2024.8.30)
  Requirement already satisfied: markdown-it-py>=2.2.0 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from rich->esp-idf-size->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 17)) (3.0.0)
  Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from rich->esp-idf-size->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 17)) (2.18.0)
  Requirement already satisfied: mdurl~=0.1 in /tmp/.embuild/espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->esp-idf-size->-r /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt (line 17)) (0.1.2)
  Installing collected packages: setuptools
    Attempting uninstall: setuptools
      Found existing installation: setuptools 75.6.0
      Uninstalling setuptools-75.6.0:
        Successfully uninstalled setuptools-75.6.0
  Successfully installed setuptools-71.0.0
  Upgrading pip and setuptools...
  Skipping the download of /tmp/.embuild/espressif/espidf.constraints.v5.1.txt because it was downloaded recently.
  Installing Python packages
   Constraint file: /tmp/.embuild/espressif/espidf.constraints.v5.1.txt
   Requirement files:
    - /tmp/.embuild/espressif/esp-idf/v5.1.3/tools/requirements/requirements.core.txt

  --- stderr
  Build configuration: BuildConfig {
      esp_idf_tools_install_dir: None,
      esp_idf_sdkconfig: None,
      esp_idf_sdkconfig_defaults: None,
      mcu: Some(
          "esp32c3",
      ),
      native: NativeConfig {
          esp_idf_version: Some(
              Tag(
                  "v5.1.3",
              ),
          ),
          esp_idf_repository: None,
          esp_idf_cmake_generator: None,
          idf_path: None,
          extra_components: [],
          esp_idf_components: None,
          esp_idf_component_manager: None,
      },
      esp_idf_sys_root_crate: None,
  }
  Using managed esp-idf repository: RemoteSdk { repo_url: None, git_ref: Tag("v5.1.3") }
  Using esp-idf v5.1.3 at '/tmp/.embuild/espressif/esp-idf/v5.1.3'

  error occurred: unknown target `riscv32imc_zicsr_zifencei-esp-espidf`
`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
-  espup:  0.13.0
- rustup
`Default host: x86_64-unknown-linux-gnu
rustup home:  /home/nirmalya/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2024-06-30-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
esp (default)

installed targets for active toolchain
--------------------------------------

riscv32imac-unknown-none-elf
riscv32imafc-unknown-none-elf
riscv32imc-unknown-none-elf
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by '/home/nirmalya/Workspace-Rust/Embedded/Rust-Embedded-By-Omar-Companion/blinky/rust-toolchain.toml')
rustc 1.84.0-nightly (bc5cf994d 2024-11-05)
`

**Additional context**
This is the picture of the SoC that I have:
![WhatsApp Image 2024-11-21 at 9 57 08 PM](https://github.com/user-attachments/assets/4139af14-a33a-4d37-b8f7-a4c98b3fad86)

This is not a bug report. I am a newbie and I don't know exactly where I am going wrong. I need help.

**Comment by theembeddedrustacean** [comment]
Hello @nsengupta ,

This is a known issue due to a recent update to the `cc-rs` crate you can find details here ->  https://github.com/esp-rs/std-training/issues/266 

There is a PR to fix this issue https://github.com/rust-lang/cmake-rs/pull/225 , though until it is merged, as a workaround, add `cc="=1.1.31"` as a dependency under `[dependencies]` in the `Cargo.toml` file.

**Comment by nsengupta** [comment]
> add cc="=1.1.31" as a dependency under [dependencies] in the Cargo.toml file.

Many thanks for this. I realize that if I generate using the template ( `esp-rs/esp-idf-template` ), this line is automatically added to the `Cargo.toml` file. 

However, after effecting that change in the `Cargo.toml`, the code is flashed alright, but it doesn't work. Here's the output:

```Running 'espflash flash --monitor target/riscv32imc-esp-espidf/debug/blinky'
[2024-11-22T15:48:46Z INFO ] Serial port: '/dev/ttyUSB0'
[2024-11-22T15:48:46Z INFO ] Connecting...
[2024-11-22T15:48:46Z INFO ] Using flash stub
Chip type:         esp32 (revision v3.1)
Crystal frequency: 40 MHz
Flash size:        4MB
Features:          WiFi, BT, Dual Core, 240MHz, Embedded Flash, VRef calibration in efuse, Coding Scheme None
MAC address:       cc:7b:5c:02:4e:94
App/part. size:    509,328/4,128,768 bytes, 12.34%
[2024-11-22T15:48:48Z INFO ] Segment at address '0x1000' has not changed, skipping write
[2024-11-22T15:48:48Z INFO ] Segment at address '0x8000' has not changed, skipping write
[00:00:25] [========================================]     245/245     0x10000                                                                                                                 [2024-11-22T15:49:14Z INFO ] Flashing has completed!
Commands:
    CTRL+R    Reset chip
    CTRL+C    Exit

ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7104
load:0x40078000,len:15576
load:0x40080400,len:4
ho 8 tail 4 room 4
load:0x40080404,len:3876
entry 0x4008064c
I (32) boot: ESP-IDF v5.1-beta1-378-gea5e0ff298-dirt 2nd stage bootloader
I (32) boot: compile time Jun  7 2023 07:48:23
I (34) boot: Multicore bootloader
I (38) boot: chip revision: v3.1
I (42) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (51) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (61) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (72) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (79) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (87) boot:  2 factory          factory app      00 00 00010000 003f0000
I (94) boot: End of partition table
I (99) esp_image: segment 0: paddr=00010020 vaddr=3c060020 size=0ffd8h ( 65496) load
E (107) esp_image: Segment 0 0x3c060020-0x3c06fff8 invalid: bad load address range
E (115) boot: Factory app partition is not bootable
E (121) boot: No bootable app partitions in the partition table
ets Jul 29 2019 12:21:46

```

Not sure if it is because of any specific attribute of the SoC.

**Comment by nsengupta** [comment]
I have made a little more progress.
In the `wokwi.toml`, I have made the path to target, explicit, like this:
```[wokwi]
version = 1
gdbServerPort = 3333
elf = "./target/riscv32imc-esp-espidf/debug/blinky"
firmware = "./target/riscv32imc-esp-espidf/debug/blinky"
```
And, then, I could simulate the Wokwi version, correctly.  W/o this change, Wokwi simulator on my VisualCode IDE failed.

So, the Wokwi simulation **works fine**, but flashing to the **connected SoC doesn't**. 

Note: for reason I still don't know, _cargo_  was creating the _target_  under `/tmp` directory. So, I had overriden that by specifying the `target-dir` in the `cargo run` command (Ubuntu 22.10).

Not sure if this information is of any help, but I think it is important to share.

**Comment by theembeddedrustacean** [comment]
Hello @nsengupta ,

The code you are generating is for a different hardware target than the one you have. The code is being generated for the ESP32-C3 with the RISC-V architecture, while the hardware you shared in the picture is an ESP32, which is based on the Xtensa architecture. 

The good news is that the same book repository has branches to support the different devices, including the ESP32. So, if you switch to the [esp32dkc branch](https://github.com/theembeddedrustacean/ser-std/tree/esp32dkc), then the code should work with your hardware.

**Comment by nsengupta** [comment]
Hello Omar (@theembeddedrustacean)

I have followed your suggestions, have gone through the Esp-RS pages once more and then I have established that the following combination seems to work on the SoC itself.

###  ./cargo/config.toml
```rust
build]
#target = "riscv32imc-esp-espidf"  #--Replaced this
target = "xtensa-esp32-espidf"      #--With this
target-dir = "./target"

#[target.riscv32imc-esp-espidf]  #--Replaced this
[target.xtensa-esp32-espidf]      #--With this
linker = "ldproxy"
runner = "espflash flash --monitor" # Select this runner for espflash v3.x.x
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
#MCU="esp32c3" #--Replaced this
MCU="esp32"    #--With this
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.2"

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174 
CRATE_CC_NO_DEFAULTS = "1"
```
### rust-toolchain.txt
```rust
[toolchain]
#channel = "nightly"       #--Replaced this
channel = "esp"             #--With this
components = ["rust-src"]
```
###  Cargo.tom
```rust
[build-dependencies]
embuild = "0.32.0"
cc = "=1.1.31" #--Refer to this (https://github.com/rust-lang/cmake-rs/pull/225)
```

Then, I run this command:
`cargo +esp run --target-dir "./target"` 

The output is much more encouraging:

```rust
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7104
load:0x40078000,len:15576
load:0x40080400,len:4
0x40080400 - _invalid_pc_placeholder
    at ??:??
ho 8 tail 4 room 4
load:0x40080404,len:3876
entry 0x4008064c
I (32) boot: ESP-IDF v5.1-beta1-378-gea5e0ff298-dirt 2nd stage bootloader
I (32) boot: compile time Jun  7 2023 07:48:23
I (34) boot: Multicore bootloader
I (38) boot: chip revision: v3.1
I (42) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (51) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (61) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (72) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (79) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (87) boot:  2 factory          factory app      00 00 00010000 003f0000
I (94) boot: End of partition table
I (99) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=1e4f8h (124152) map
I (152) esp_image: segment 1: paddr=0002e520 vaddr=3ffb0000 size=01af8h (  6904) load
I (155) esp_image: segment 2: paddr=00030020 vaddr=400d0020 size=4cd28h (314664) map
I (271) esp_image: segment 3: paddr=0007cd50 vaddr=3ffb1af8 size=00660h (  1632) load
I (272) esp_image: segment 4: paddr=0007d3b8 vaddr=40080000 size=0be60h ( 48736) load
I (303) boot: Loaded app from partition at offset 0x10000
I (303) boot: Disabling RNG early entropy source...
I (315) cpu_start: Multicore app
I (324) cpu_start: Pro cpu start user code
I (324) cpu_start: cpu freq: 160000000 Hz
I (324) cpu_start: Application information:
I (327) cpu_start: Project name:     libespidf
I (332) cpu_start: App version:      1
I (336) cpu_start: Compile time:     Nov 26 2024 19:02:58
I (342) cpu_start: ELF file SHA256:  000000000...
I (348) cpu_start: ESP-IDF:          v5.2.2
I (353) cpu_start: Min chip rev:     v0.0
I (357) cpu_start: Max chip rev:     v3.99 
I (362) cpu_start: Chip rev:         v3.1
I (367) heap_init: Initializing. RAM available for dynamic allocation:
I (374) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (380) heap_init: At 3FFB2A98 len 0002D568 (181 KiB): DRAM
I (386) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (393) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (399) heap_init: At 4008BE60 len 000141A0 (80 KiB): IRAM
I (407) spi_flash: detected chip: generic
I (410) spi_flash: flash io: dio
W (414) pcnt(legacy): legacy driver is deprecated, please migrate to `driver/pulse_cnt.h`
W (423) timer_group: legacy driver is deprecated, please migrate to `driver/gptimer.h`
I (432) main_task: Started on CPU0
I (442) main_task: Calling app_main()
I (442) devkitm_1_std_esp_blinky: Hello, world!
I (442) main_task: Returned from app_main()
```

The problem is that for us, the beginners, the small differences in the SoC are not so obvious that we can easily reach the source of the problem and then, fix it. I have shared the picture of the SoC that I have purchased. It clearly says that it is **ESP32-MINI-1**. The documents that came along with mentions this to be a **Esp32-C3-Devkit-M-1*, exactly as the book suggests. However, there is nothing else that explicitly tells me where the differences are.  For example, the following is the output of `espflash board-info`:

```bash
[2024-11-26T13:49:28Z INFO ] Serial port: '/dev/ttyUSB0'
[2024-11-26T13:49:28Z INFO ] Connecting...
[2024-11-26T13:49:28Z INFO ] Using flash stub
Chip type:         esp32 (revision v3.1)
Crystal frequency: 40 MHz
Flash size:        4MB
Features:          WiFi, BT, Dual Core, 240MHz, Embedded Flash, VRef calibration in efuse, Coding Scheme None
MAC address:       cc:7b:5c:02:4e:94
```

I should have realized that the chipt-type being just **esp32**, I should have expected somewhat rough weather because that 'c3' is missing.  Unfortunately, this is **not** explicit anywhere. I sought help in the Discord channel and good folks there nudged me to right direction. On my part, I have gone through the github pages of ESP-RS, a few times. 

Obviously, all these have helped me to learn significantly. I am also more comfortable with the tool-chain and build/flash process.

Thank you for all your responses. BTW, I am liking the book. :relaxed: , :+1:

**Comment by theembeddedrustacean** [comment]
Glad it worked @nsengupta, I will be closing this issue now since it is not a repo issue and seems to be resolved on your end.
